spring:
  application:
    name: skillifymevideo
  data:
    mongodb:
      uri: ${mongo_uri}
      database: SkillifyMe
      auto-index-creation: true
      username: ${mongo_password}
      password: ${mongo_password}
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
media:
  file:
    base-path: /path/to/your/media/files/
access:
  key:
    id: ${access_key}
    secret: ${access_secret}
s3:
  region:
    name: ap-southeast-2
  bucket:
    name: skillifymestorage
