spring:
  application:
    name: Skillifymevideo
  data:
    mongodb:
      uri: ${mongo_uri}
      database: SkillifyMe
      auto-index-creation: true
      username: ${mongo_password}
      password: ${mongo_password}
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
